name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: samin/mysql-action@v1
        with:
          mysql version: '5.7'
          mysql database: ${{ secrets.TEST_DATABASE }}
          mysql user: ${{ secrets.DATABASE_USER }}
          mysql password: ${{ secrets.DATABASE_PASS }}
              
      - name: Wait for MYSQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=${{ secrets.DATABASE_PASS }} --silent; do
            sleep 1
          done
            
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      
      - name: Update database 
        run: php bin/console doc:mig:mig --no-interaction --env=test

      - name: Load fixture
        run: bin/console doc:fix:load --no-interaction --group=APP --group=TEST --env=test

      - name: Run tests
        run: php ./vendor/bin/phpunit
        
